apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../podmonitor
- scc.yaml
- scc-role.yaml
- datasource.yaml
- dashboard.yaml
patches:
- patch: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kubevirt-metrics-exporter
      labels:
        openshift.io/cluster-monitoring: "true"
  target:
    kind: Namespace
    name: kubevirt-metrics-exporter
- patch: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: kubevirt-metrics-exporter
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
  target:
    kind: DaemonSet
    name: kubevirt-metrics-exporter
images:
- name: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newName: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newTag: latest
